# Generated by Django 2.1.1 on 2018-11-27 05:07

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='comment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content', models.CharField(max_length=255)),
                ('time', models.DateTimeField()),
            ],
        ),
        migrations.CreateModel(
            name='content',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20)),
                ('original', models.CharField(max_length=255)),
                ('note', models.CharField(max_length=255)),
                ('translation', models.CharField(max_length=255)),
                ('image', models.CharField(max_length=255)),
            ],
        ),
    ]
